import{a as L,S as w,i as I}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const x="/goit-js-hw-12/assets/bi_x-octagon-4f06a8ee.svg",f="/goit-js-hw-12/assets/closebi_x-lg-de5d3efc.svg";async function h(t,r=1,s=15){const n="45065033-34b48c3d2ea0e7ba665d8e642",e="https://pixabay.com/api/",o={key:n,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:s};try{return(await L.get(e,{params:o})).data.hits}catch(a){return S(a),[]}}function S(t){if(t.response)switch(t.response.status){case 404:console.error("Images not found"),alert("Images not found");break;case 500:console.error("Server error"),alert("Server error");break;default:console.error(`Error: ${t.response.status}`),alert(`Error: ${t.response.status}`)}else t.request?(console.error("Check your internet connection:"),alert("Internet connection lost !")):(console.error("Error setting up the request:",t.message),alert("Error setting up the request"))}function y(t){const r=document.getElementById("image-container");if(r.innerHTML="",t.length>0){const s=t.map(e=>`
      <li class="gallery-link">
        <a class="card-link" href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
          <div class="card">
            <img class="image" src="${e.webformatURL}" alt="${e.tags}">
            <div class="card-points">
              <div class="card-text"><p>Likes: ${e.likes}</p></div>
              <div class="card-text"><p>Views: ${e.views}</p></div>
              <div class="card-text"><p>Comments: ${e.comments}</p></div>
              <div class="card-text"><p>Downloads: ${e.downloads}</p></div>
            </div>
          </div>
        </a>
      </li>
    `);r.innerHTML=s.join(""),new w('[data-lightbox="gallery"]').refresh()}}const v=document.querySelector("#search-form"),l=document.getElementById("loader"),i=document.getElementById("loadButton"),$=document.getElementById("image-container");let c="",d=1;const b=15;function g(t,r,s=3e3){I.show({position:"topRight",message:t,backgroundColor:"#EF4040",messageColor:"#fff",messageSize:"16",maxWidth:432,iconUrl:x,timeout:s,class:"iziToast-custom",onOpening:function(n,e){const o=document.createElement("div");o.className="custom-icon",o.style.backgroundImage=`url(${r})`,e.querySelector(".iziToast-message").appendChild(o)}})}async function q(t){if(t.preventDefault(),c=document.querySelector("#search-input").value.trim(),c){d=1,m(),E();try{const r=await h(c,d,b);u(),r.length>0?(y(r),i.style.display="block"):p()}catch(r){u(),console.error("Error searching images:",r),g(r.message,f,3e3),m()}}else p();v.reset()}function p(){g("Sorry, there are no images matching your search query. Please try again!",f,3e3),m()}function m(){$.innerHTML=""}function E(){l?l.classList.add("visible"):console.error("Loader not found")}function u(){l?l.classList.remove("visible"):console.error("Loader not found")}async function C(){E();try{const t=await h(c,d,b);t.length>0?(y(t),d++,i.style.display="block"):(i.style.display="none",u(),g("We're sorry, but you've reached the end of search results.",f,3e3))}catch(t){console.error("Error fetching images:",t),i.textContent="Failed to load more"}u()}v.addEventListener("submit",q);i.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
