import{a as L,S as w,i as x}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(r){if(r.ep)return;r.ep=!0;const e=a(r);fetch(r.href,e)}})();const I="/goit-js-hw-12/assets/bi_x-octagon-4f06a8ee.svg",l="/goit-js-hw-12/assets/closebi_x-lg-de5d3efc.svg",S="45065033-34b48c3d2ea0e7ba665d8e642";async function p(t,o=1,a=15){const s="https://pixabay.com/api/",r={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:a};try{const e=await L.get(s,{params:r}),{hits:i,totalHits:E}=e.data;return console.log("API response:",i),console.log("Current page:",o),{hits:i,totalHits:E}}catch(e){return q(e),{hits:[],totalHits:0}}}function q(t){if(t.response)switch(t.response.status){case 404:console.error("Images not found");break;case 500:console.error("Server error");break;default:console.error(`Error: ${t.response.status}`)}else t.request?console.error("Check your internet connection:"):console.error("Error setting up request:",t.message)}function v(t){const o=document.getElementById("image-container");if(Array.from(o.querySelectorAll(".gallery-link")),t.length>0){const s=t.map(e=>`
      <li class="gallery-link">
        <a class="card-link" href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
          <div class="card">
          <div id="loader" class="loader" aria-live="polite" role="status"></div>
            <img class="image" src="${e.webformatURL}" alt="${e.tags}">
            <div class="card-points">
              <div class="card-text"><p>Likes: ${e.likes}</p></div>
              <div class="card-text"><p>Views: ${e.views}</p></div>
              <div class="card-text"><p>Comments: ${e.comments}</p></div>
              <div class="card-text"><p>Downloads: ${e.downloads}</p></div>
            </div>
          </div>
        </a>
      </li>
    `).join("");o.innerHTML+=s,new w('[data-lightbox="gallery"]').refresh()}document.querySelectorAll(".image").forEach(s=>{s.onload=()=>{s.previousElementSibling.style.display="none"}})}const b=document.querySelector("#search-form");document.getElementById("loader");const n=document.getElementById("loadButton");document.querySelector(".submit");const k=document.getElementById("image-container"),m=document.getElementById("search-input");let u="",c=1;const h=15;function d(t,o,a=3e3){x.show({position:"topRight",message:t,backgroundColor:"#EF4040",messageColor:"#fff",messageSize:"16",maxWidth:432,iconUrl:I,timeout:a,class:"iziToast-custom",onOpening:(s,r)=>{const e=document.createElement("div");e.className="custom-icon",e.style.backgroundImage=`url(${o})`,r.querySelector(".iziToast-message").appendChild(e)}})}async function C(t){if(t.preventDefault(),u=document.querySelector("#search-input").value.trim(),u){c=1,n.removeEventListener("click",g),f();try{const{hits:o,totalHits:a}=await p(u,c,h);o&&o.length>0?(v(o),n.style.display="block",n.addEventListener("click",g),o.length>=a&&(n.style.display="none",d("We're sorry, but you've reached the end of search results.",l,3e3))):y()}catch(o){console.error("Error searching images:",o),d(o.message,l,3e3),f()}}else y();b.reset()}function y(){d("Sorry, there are no images matching your search query. Please try again!",l,3e3),f(),n.style.display="none"}function f(){k.innerHTML=""}async function g(){c++,console.log("Loading images..."),console.log("Current page:",c);try{const{hits:t,totalHits:o}=await p(u,c,h);console.log("Fetched hits:",t),console.log("Total hits:",o),t.length>0?(v(t),setTimeout(B,500),c*h>=o?(n.style.display="none",d("We're sorry, but you've reached the end of search results.",l,3e3),n.removeEventListener("click",g)):n.style.display="block"):(n.style.display="none",d("We're sorry, but you've reached the end of search results.",l,3e3))}catch(t){console.error("Error fetching images:",t),n.removeEventListener("click",g)}}b.addEventListener("submit",C);function $(){const t=document.querySelector(".card");return t?t.getBoundingClientRect().height:0}function B(){const t=$();t>0&&window.scrollBy({top:2*t,behavior:"smooth"})}m.addEventListener("blur",()=>{m.style.border=m.value?"4px solid green":"4px solid red"});
//# sourceMappingURL=commonHelpers.js.map
